EMBEDDING_DIM = 300
MAX_SEQUENCE_LENGTH_WITHOUT_AUG = 23
MAX_SEQUENCE_LENGTH_WITH_AUG = 40
VALIDATION_SIZE = 0.1
NUMBER_LSTM_UNITS = 100
RATE_DROP_LSTM = 0.3
NUMBER_DENSE_UNITS = 50
RATE_DROP_DENSE = 0.25
ACTIVATION_FUNCTION = 'relu'

# Siamese Config Dictionary #
Siamese_Config = {
    'EMBEDDING_DIM': EMBEDDING_DIM,
    'MAX_SEQUENCE_LENGTH_WITHOUT_AUG': MAX_SEQUENCE_LENGTH_WITHOUT_AUG,
    'MAX_SEQUENCE_LENGTH_WITH_AUG': MAX_SEQUENCE_LENGTH_WITH_AUG,
    'VALIDATION_SIZE': VALIDATION_SIZE,
    'NUMBER_LSTM_UNITS': NUMBER_LSTM_UNITS,
    'RATE_DROP_LSTM': RATE_DROP_LSTM,
    'NUMBER_DENSE_UNITS': NUMBER_DENSE_UNITS,
    'RATE_DROP_DENSE': RATE_DROP_DENSE,
    'ACTIVATION_FUNCTION': ACTIVATION_FUNCTION
}
